# Generated by Django 3.2 on 2021-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20210424_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAirportalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='airportal')),
                ('createTime', models.DateTimeField()),
                ('hours', models.DurationField()),
                ('downloads', models.CharField(max_length=5)),
                ('pickupCode', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
